var refreshInterval = 1000*60; //time in milliseconds
var timeLeft = refreshInterval / 1000; //variable for keeping track of the countdown

$(function() { //onload, runs when page finishes loading
	fetchDeviceStatus();
	var intervalRefresh = setInterval("fetchDeviceStatus()",refreshInterval);
	var intervalTimer = setInterval("updateTimer()",1000);
});

//decrements timeLeft by 1, stops at 0
//updates the refresh indicator text
function updateTimer() {
	timeLeft = Math.max(timeLeft-1,0);
	$("div#refresh").html("This page will refresh in " + timeLeft + " seconds");	
}

//updates printer statuses
//pings each printer's device status page, parses text out of html
//places html object into appropriate category
function fetchDeviceStatus() {
	timeLeft = refreshInterval / 1000;

	$("div#noresponse").hide();
	$("div#urgent div").remove();
	$("div#noresponse div").remove();
	$("div#needservice div").remove();
	$("div#goodservice div").remove();
	
	//iterate through printers
	//printers defined in printers.js
	for (var i=0; i<printers.length; i++) {
		var printer = printers[i];
		//if ((printer.type == "HPM806") || (printer.type == "HP651")) {
		//	fetchDeviceStatusHPM806(printer);
		//} 
		if (printer.type == "HPM806") {
			fetchDeviceStatusHPM806(printer);	
		} else if (printer.type == "HPM651") {
			fetchDeviceStatusHPM651(printer);
		}

	}
			
	for (var i=0; i<printers.length; i++) {
		if (printers[i]["error"])
			alert('error logged');
	}
}


function fetchDeviceStatusHPM806(printer) {


	var urlDeviceStatus = "http://" + printer.ip + "/hp/device/DeviceStatus/index";
	
	//create a jQuery HTML object to be added to the "no response category"
	//this will be removed later in this function if/when printer responds to HTTP request
	var divPending = $("<div>")
		.attr('class',"printerBox pending"+printer.nameShort)
		;
		

	//Printer Name
	var printerName = $("<div>")
		.attr('class','printerTitle')
		.html(" <a href=\"" + urlDeviceStatus + "\" target='_new'>"+printer.name+"</a>");
	divPending.append(printerName);
		
	//Printer Status Page
	var printerStatus = $("<div>")
		.attr('class','cell')
		.html("[<a href=\"" + urlDeviceStatus + "\" target='_new'>Status Page</a>]")
		;
	divPending.append(printerStatus);
	
	$("div#noresponse").show().append(divPending);

	
	//jQuery call to make HTTP POST request to fetchUrl.php
	//append a random integer to querystring to prevent returning a cached version of the page
	//pass the url of the printer device status page and the printer object
	//	also another random number for the same reason
	
	$.post("fetchUrl.php?rnd="+Math.random(),{url:urlDeviceStatus,printer:printer,rnd:Math.random()}, function(data)


 { //if the printer responds to the HTTP request, this function will run
	//data is the HTML generated by the device status page by way of fetchUrl.php
		
		console.log("Starting \t" + printer.name);

		var statusValue = 0;

		//parse returned page as HTML
		var $dataParsed = $($.parseHTML(data));
		
		//in this state, the element in position 1 will be the text of the current status
		//get status
		var currentStatus = $dataParsed.find("#MachineStatus").html();
						
		//parse out the text "Cartridge...%"
		//then parse out the numbers from that string to get the toner level
		//get toner
		var currentToner = $.trim($dataParsed.find("#SupplyPLR0").html()).replace('*', '');				

		//parse out the text "Maintenance Kit...%"
		//then parse out the numbers from that string to get the maintenance kit level
		//get maintenance
	
		var currentMaintenance = $.trim($dataParsed.find("#SupplyPLR1").html()).replace('*', '');
		
		var trays = [];

		//temp tray for loop
		var curTrayName	= '1'; //do while loop once
		var curTrayStatus;
		var curTraySize;
		var curTrayType;

		//tray counter for loop
		var i = 1;

		//while next #TrayBinName_i div is found)
		while(curTrayName) {
			//get tray data
			curTrayName		= $.trim( $dataParsed.find("#TrayBinName_"+i).html() );
			curTrayStatus	= $.trim( $dataParsed.find("#TrayBinStatus_"+i).html() );
			curTraySize		= $.trim( $dataParsed.find("#TrayBinSize_"+i).html() );
			curTrayType		= $.trim( $dataParsed.find("#TrayBinType_"+i).html() );

			//check if tray exists and contains the word 'Tray' in name before pushing
			//(should exclude manual feeds)
			if(curTrayName.search("Tray") > -1) {
				trays.push({
					name:	curTrayName,
					status:	curTrayStatus,
					size:	curTraySize,
					type:	curTrayType
				});
			}
			
			//increment tray/loop counter
			i++;
		}
		
		//create a jQuery printerBox element to format/arrange the status information
		var printerBox = $("<div>").attr('class','printerBox');
		
		//Printer Name
		var printerName = $("<div>")
			.attr('class','printerTitle')
			.html("<a href=\"http://" + printer.ip + "/hp/device/DeviceStatus/Index\" target='_new'>"+printer.name+"</a>")
			;
		printerBox.append(printerName);
		
		//add current status
		//change color based on status
		var divCurrentStatus = $("<div>")
			.attr('class','cell')
			.html("Status: "+currentStatus);

		//parse text of the current target='_new'>"+printer.name+"</a>")
			;status
		//if it contains jam/'load tray 1'/error/open, decrement status value by 3
		//this ensures that these statuses will put the printer in Urgent state
		//other than that, it's fine
		if (currentStatus.match(/(jam)|(load\ tray\ 1)|(error)|(open)|(CLOSE\ FRONT\ OR\ LEFT\ DOOR)/i)) {
			divCurrentStatus.css('borderLeftColor','red');
			statusValue -= 3;
		} else if (currentStatus.match(/(ready)/i)) {
			divCurrentStatus.css('borderLeftColor','green');
		} else {
			divCurrentStatus.css('borderLeftColor','orange');
			statusValue += 0.2;
		}
		printerBox.append(divCurrentStatus);
		
		//Toner & Maintenance
		var divTNM = $("<div>")
			.attr('class','cellTitle')
			.html("Toner &amp; Maintenance")
		;
		printerBox.append(divTNM);
		
		//add current toner
		//change background color based on status
		//less than 1% will decrement status value by 3, puts printer in Urgent state
		//less than 5% will incrememt status value by 0.3
		//otherwise, increment status value by 1.0
		var divCurrentToner = $("<div>")
			.attr('class','cell')
			.html("Toner: "+currentToner)
		;		
		if (currentToner == "N/A") {	
			divCurrentToner.css('borderLeftColor','orange');
			statusValue += 0.0;
		} else if (Number(currentToner.match(/\d+/)[0]) < 1) {
			divCurrentToner.css('borderLeftColor','red');
			statusValue -= 3;
		} else if (Number(currentToner.match(/\d+/)[0]) < 10) {
			divCurrentToner.css('borderLeftColor','orange');
			statusValue += 0.3;
		} else {
			divCurrentToner.css('borderLeftColor','green');
			statusValue += 1;
		}
		printerBox.append(divCurrentToner);
		
		//add current mainteance kit
		//change color based on status
		//less than 5% will decrease status value by 0.5
		//otherwise, increment status value by 0.5
		var divCurrentMaintenance = $("<div>")
			.attr('class','cell')
			.html("Maintenance Kit: "+currentMaintenance)
			;
		if (currentMaintenance == "--%") {
			divCurrentMaintenance.css('borderLeftColor','orange');
			statusValue += 0.5;
		} else if (Number(currentMaintenance.match(/\d+/)[0]) < 5) {
			divCurrentMaintenance.css('borderLeftColor','orange');
			statusValue -= 0.5;
		} else {
			divCurrentMaintenance.css('borderLeftColor','green');
			statusValue += 0.5;
		}
		printerBox.append(divCurrentMaintenance);
		
		// Paper Trays
		var divPT = $("<div>")
			.attr('class','cellTitle')
			.html("Paper Trays")
		;
		printerBox.append(divPT);
		
		//iterate through trays
		//keep track of total tray count, if Tray 1 exists, decrement tray count by 1
		//if tray status reads "OK" increment status value by (1/trayCount)
		//	if all trays that are not Tray 1 are OK, status value will increase by 1.0
		//if tray status has numbers in it
		//	parse out the number
		//		if it's 40,  increment status value by (1/trayCount), make it green
		//		if it's 10, make it orange, don't increment status value
		var trayCount = trays.length;
		for (var i=0; i<trays.length; i++) {
			var tray = trays[i];
			var divTray = $("<div>")
				.attr('class','cell')
				.html(tray.name + ": " + tray.status)
				;

			if (tray.name.match(/tray\s1/i)) {
				trayCount--;
			} else {
				if (tray.status.match(/ok/i)) {
					divTray.css('borderLeftColor','green');
					statusValue += 1/trayCount;
				} else if (tray.status.match(/\d+/)) {
					if (Number(tray.status.match(/\d+/)[0]) >= 40) {
						divTray.css('borderLeftColor','green');
						statusValue += 1/trayCount;						
					} else if (Number(tray.status.match(/\d+/)[0]) >= 10) {
						divTray.css('borderLeftColor','orange');
					
					} else {
						divTray.css('borderLeftColor','red');
					}
				} else {
					divTray.css('borderLeftColor','red');
				}
			}
				
			
			printerBox.append(divTray);
		}
		
		// Displays the status value, integer for determing which category to place printer in
		//Uncomment for testing/debugging
		//divMathFloor = $("<div>")
		//	.attr('class','cell')
		//	.html(Math.floor(statusValue))
		//	;
		//printerBox.append(divMathFloor);
		
		//remove this printer from the "no response" section
		//if there are no more printers in the "no response" section, hide it
		$("div.pending"+printer.nameShort).remove();
		var divNoResponse = $("div",$("div#noresponse"));
		if (divNoResponse.size() == 0)
			$("div#noresponse").hide();				

		//determine which category the printer should be added to by its status value
		if (Math.floor(statusValue) < 1) {
			$("div#urgent").show().append(printerBox);
			alert(printer.name + " NEEDS SERVICE IMMEDIATELY");
		} else if (Math.floor(statusValue) < 2) {
			$("div#needservice").show().append(printerBox);
		} else {
			$("div#goodservice").show().append(printerBox);
		}
	})
	.error( function() {
		//printers[i]["error"] = true;
	});

}


function fetchDeviceStatusHP806(printer) {

	var urlDeviceStatus = "http://" + printer.ip + "/hp/device/DeviceStatus/Index";
	
	//create a jQuery HTML object to be added to the "no response category"
	//this will be removed later in this function if/when printer responds to HTTP request
	var divPending = $("<div>")
		.attr('class',"printerBox pending"+printer.nameShort)
		;
		
	//Printer Name
	var printerName = $("<div>")
		.attr('class','printerTitle')
		.html("<a href=\"http://" + printer.ip + "/hp/device/DeviceStatus/Index\" target='_new'>"+printer.name+"</a>")
		;
	divPending.append(printerName);
		
	//Printer Status Page
	var printerStatus = $("<div>")
		.attr('class','cell')
		.html("[<a href=\"" + urlDeviceStatus + "\">Status Page</a>]")
		;
	divPending.append(printerStatus);
	
	$("div#noresponse").show().append(divPending);

	//jQuery call to make HTTP POST request to fetchUrl.php
	//append a random integer to querystring to prevent returning a cached version of the page
	//pass the url of the printer device status page and the printer object
	//	also another random number for the same reason
	$.post("fetchUrl.php?rnd="+Math.random(),{url:urlDeviceStatus,printer:printer,rnd:Math.random()}, function(data) { //if the printer responds to the HTTP request, this function will run
	//data is the HTML generated by the device status page by way of fetchUrl.php
		var strHTML = data;
		var statusValue = 0;
				
		//parse out the printer object data that's been appended to the HTML by fetchUrl.php
		var strPrinterData = strHTML.match(/\[printerData\].*\[\/printerData\]/)[0];
		strPrinterData = strPrinterData.replace(/\[\/*printerData\]/g,'');
		var printer = $.parseJSON(strPrinterData);
				
		//get the HTML data starting from a specific spot on the page
		//remove all HTML tags
		//remove all HTML comments
		//replace instances of multiple line breaks in a row with a single line break
		//create an array from this text, separating elements by line breaks
		var strForm = strHTML.match(/\<form\sid=\"deviceStatusPage\".*[\s\S]*/)[0];
		var strFormNoTags = strForm.replace(/\<.*\>/g,'')
			.replace(/\<!--.*[\s\S]*--\>/g,'')
			.replace(/\n+/g,'\n');
		var aryDeviceStatus = strFormNoTags.split('\n');
		
		//in this state, the element in position 1 will be the text of the current status
		//get status
		var currentStatus = aryDeviceStatus[1];
						
		//parse out the text "Cartridge...%"
		//then parse out the numbers from that string to get the toner level
		//get toner
		var currentToner = "N/A";
		var currentTonerPercentage;
		currentTonerPercentage = strFormNoTags.match(/.*Cartridge.*%.*\n/i);
		
		if (currentTonerPercentage)
			currentToner = currentTonerPercentage[0].match(/\d+.*\n/)[0];				

		//parse out the text "Maintenance Kit...%"
		//then parse out the numbers from that string to get the maintenance kit level
		//get maintenance
		var strCurrentMK = strFormNoTags.match(/.*Maintenance\sKit.*%.*\n/);
		if (strCurrentMK)
			var currentMaintenance = strFormNoTags.match(/.*Maintenance\sKit.*%.*\n/)[0].match(/\d+.*\n/)[0];
		else
			var currentMaintenance = "N/A";
		
		//get a chunk of the text that starts with "Media" and ends in "</table>"
		//replace ">" with ">" followed by a line break
		//remove all HTML tags
		//replace instances of multiple line breaks in a row with a single line break
		//remove all instances of "&nbsp;", the javascript space character
		//result will be several lines of text with the tray information
		//put this into an array
		//get trays
		var strTrays = strHTML.match(/Media.*[\s\S]*\<\/table\>/gm)[0];
		var strTraysNoTags = strTrays.replace(/\>/g,'>\n')
			.replace(/\<.*\>/g,'')
			.replace(/\n+/g,'\n')
			.replace(/\&nbsp;/g,'');
		var aryTrays = strTraysNoTags.split('\n');
		var trays = [];

		//iterate through the array of tray information
		for (var i=0; i<aryTrays.length; i++) {
			var line = aryTrays[i];

			//if the element of the array contains "Tray #"
			//the following three elements will be status, size, and type
			if (line.match(/^Tray\s\d+/)) {
				trays.push({
					name:aryTrays[i],
					status:aryTrays[i+1],
					size:aryTrays[i+2],
					type:aryTrays[i+3]
				});
			}
		}
		
		//create a jQuery printerBox element to format/arrange the status information
		var printerBox = $("<div>").attr('class','printerBox');
		
		//Printer Name
		var printerName = $("<div>")
			.attr('class','printerTitle')
			.html("<a href=\"http://" + printer.ip + "/hp/device/DeviceStatus/Index\" target='_new'>"+printer.name+"</a>")
			;
		printerBox.append(printerName);
		
		//add current status
		//change color based on status
		var divCurrentStatus = $("<div>")
			.attr('class','cell')
			.html("Status: "+currentStatus);

		//parse text of the current status
		//if it contains jam/'load tray 1'/error/open, decrement status value by 3
		//this ensures that these statuses will put the printer in Urgent state
		//other than that, it's fine
		if (currentStatus.match(/(jam)|(load\ tray\ 1)|(error)|(open)|(CLOSE\ FRONT\ OR\ LEFT\ DOOR)/i)) {
			divCurrentStatus.css('borderLeftColor','red');
			statusValue -= 3;
		} else if (currentStatus.match(/(ready)/i)) {
			divCurrentStatus.css('borderLeftColor','green');
		} else {
			divCurrentStatus.css('borderLeftColor','orange');
			statusValue += 0.2;
		}
		printerBox.append(divCurrentStatus);
		
		//Toner & Maintenance
		var divTNM = $("<div>")
			.attr('class','cellTitle')
			.html("Toner &amp; Maintenance")
		;
		printerBox.append(divTNM);
		
		//add current toner
		//change background color based on status
		//less than 1% will decrement status value by 3, puts printer in Urgent state
		//less than 5% will incrememt status value by 0.3
		//otherwise, increment status value by 1.0
		var divCurrentToner = $("<div>")
			.attr('class','cell')
			.html("Toner: "+currentToner)
		;		
		if (currentToner == "N/A") {	
			divCurrentToner.css('borderLeftColor','orange');
			statusValue += 0.0;
		} else if (Number(currentToner.match(/\d+/)[0]) < 1) {
			divCurrentToner.css('borderLeftColor','red');
			statusValue -= 3;
		} else if (Number(currentToner.match(/\d+/)[0]) < 10) {
			divCurrentToner.css('borderLeftColor','orange');
			statusValue += 0.3;
		} else {
			divCurrentToner.css('borderLeftColor','green');
			statusValue += 1;
		}
		printerBox.append(divCurrentToner);
		
		//add current mainteance kit
		//change color based on status
		//less than 5% will decrease status value by 0.5
		//otherwise, increment status value by 0.5
		var divCurrentMaintenance = $("<div>")
			.attr('class','cell')
			.html("Maintenance Kit: "+currentMaintenance)
			;
		if (currentMaintenance == "N/A") {
			divCurrentMaintenance.css('borderLeftColor','orange');
			statusValue += 0.5;
		} else if (Number(currentMaintenance.match(/\d+/)[0]) < 5) {
			divCurrentMaintenance.css('borderLeftColor','orange');
			statusValue -= 0.5;
		} else {
			divCurrentMaintenance.css('borderLeftColor','green');
			statusValue += 0.5;
		}
		printerBox.append(divCurrentMaintenance);
		
		// Paper Trays
		var divPT = $("<div>")
			.attr('class','cellTitle')
			.html("Paper Trays")
		;
		printerBox.append(divPT);
		
		//iterate through trays
		//keep track of total tray count, if Tray 1 exists, decrement tray count by 1
		//if tray status reads "OK" increment status value by (1/trayCount)
		//	if all trays that are not Tray 1 are OK, status value will increase by 1.0
		//if tray status has numbers in it
		//	parse out the number
		//		if it's 40,  increment status value by (1/trayCount), make it green
		//		if it's 10, make it orange, don't increment status value
		var trayCount = trays.length;
		for (var i=0; i<trays.length; i++) {
			var tray = trays[i];
			var divTray = $("<div>")
				.attr('class','cell')
				.html(tray.name + ": " + tray.status)
				;

			if (tray.name.match(/tray\s1/i)) {
				trayCount--;
			} else {
				if (tray.status.match(/ok/i)) {
					divTray.css('borderLeftColor','green');
					statusValue += 1/trayCount;
				} else if (tray.status.match(/\d+/)) {
					if (Number(tray.status.match(/\d+/)[0]) >= 40) {
						divTray.css('borderLeftColor','green');
						statusValue += 1/trayCount;						
					} else if (Number(tray.status.match(/\d+/)[0]) >= 10) {
						divTray.css('borderLeftColor','orange');
					
					} else {
						divTray.css('borderLeftColor','red');
					}
				} else {
					divTray.css('borderLeftColor','red');
				}
			}
				
			
			printerBox.append(divTray);
		}
		
		// Displays the status value, integer for determing which category to place printer in
		// Uncomment for testing/debugging
		//divMathFloor = $("<div>")
		//	.attr('class','cell')
		//	.html(Math.floor(statusValue))
		//	;
		//printerBox.append(divMathFloor);
		
		//remove this printer from the "no response" section
		//if there are no more printers in the "no response" section, hide it
		$("div.pending"+printer.nameShort).remove();
		var divNoResponse = $("div",$("div#noresponse"));
		if (divNoResponse.size() == 0)
			$("div#noresponse").hide();				

		//determine which category the printer should be added to by its status value
		if (Math.floor(statusValue) < 1) {
			$("div#urgent").show().append(printerBox);
			alert(printer.name + " NEEDS SERVICE IMMEDIATELY");
		} else if (Math.floor(statusValue) < 2) {
			$("div#needservice").show().append(printerBox);
		} else {
			$("div#goodservice").show().append(printerBox);
		}
	})
	.error( function() {
		//printers[i]["error"] = true;
	});

}




function fetchDeviceStatusHPM651(printer) {

	var urlDeviceStatus = "http://" + printer.ip + "/hp/device/DeviceStatus/index";
	
	//create a jQuery HTML object to be added to the "no response category"
	//this will be removed later in this function if/when printer responds to HTTP request
	var divPending = $("<div>")
		.attr('class',"printerBox pending"+printer.nameShort)
		;
		
	//Printer Name
	var printerName = $("<div>")
		.attr('class','printerTitle')
		.html(" <a href=\"" + urlDeviceStatus + "\" target='_new'>"+printer.name+"</a>");
	divPending.append(printerName);
		
	//Printer Status Page
	var printerStatus = $("<div>")
		.attr('class','cell')
		.html("[<a href=\"" + urlDeviceStatus + "\" target='_new'>Status Page</a>]")
		;
	divPending.append(printerStatus);
	
	$("div#noresponse").show().append(divPending);

	
	//jQuery call to make HTTP POST request to fetchUrl.php
	//append a random integer to querystring to prevent returning a cached version of the page
	//pass the url of the printer device status page and the printer object
	//	also another random number for the same reason
	
	$.post("fetchUrl.php?rnd="+Math.random(),{url:urlDeviceStatus,printer:printer,rnd:Math.random()}, function(data) { //if the printer responds to the HTTP request, this function will run
	//data is the HTML generated by the device status page by way of fetchUrl.php
		
		console.log("Starting \t" + printer.name);

		var statusValue = 0;

		//parse returned page as HTML
		var $dataParsed = $($.parseHTML(data));
		
		//in this state, the element in position 1 will be the text of the current status
		//get status
		var currentStatus = $dataParsed.find("#MachineStatus").html();
						
		//parse out the text "Cartridge...%"
		//then parse out the numbers from that string to get the toner level
		//get toner
		var currentToner = $.trim($dataParsed.find("#SupplyPLR0").html()).replace('*', '');				

		//parse out the text "Cyan Cartridge...%"
		//then parse out the numbers from that string to get the maintenance kit level
		//get maintenance
		var currentCyan = $.trim($dataParsed.find("#SupplyPLR1").html()).replace('*', '');

		//parse out the text "Magenta Cartridge...%"
		//then parse out the numbers from that string to get the maintenance kit level
		//get maintenance
		var currentMagenta = $.trim($dataParsed.find("#SupplyPLR2").html()).replace('*', '');

		//parse out the text "Yellow Cartridge...%"
		//then parse out the numbers from that string to get the maintenance kit level
		//get maintenance
		var currentYellow = $.trim($dataParsed.find("#SupplyPLR3").html()).replace('*', '');

		//parse out the text "Fuser Kit...%"
		//then parse out the numbers from that string to get the maintenance kit level
		//get maintenance
		var currentMaintenance = $.trim($dataParsed.find("#SupplyPLR4").html()).replace('*', '');
		
		var trays = [];

		//temp tray for loop
		var curTrayName	= '1'; //do while loop once
		var curTrayStatus;
		var curTraySize;
		var curTrayType;

		//tray counter for loop
		var i = 1;

		//while next #TrayBinName_i div is found)
		while(curTrayName) {
			//get tray data
			curTrayName		= $.trim( $dataParsed.find("#TrayBinName_"+i).html() );
			curTrayStatus	= $.trim( $dataParsed.find("#TrayBinStatus_"+i).html() );
			curTraySize		= $.trim( $dataParsed.find("#TrayBinSize_"+i).html() );
			curTrayType		= $.trim( $dataParsed.find("#TrayBinType_"+i).html() );

			//check if tray exists and contains the word 'Tray' in name before pushing
			//(should exclude manual feeds)
			if(curTrayName.search("Tray") > -1) {
				trays.push({
					name:	curTrayName,
					status:	curTrayStatus,
					size:	curTraySize,
					type:	curTrayType
				});
			}
			
			//increment tray/loop counter
			i++;
		}
		
		//create a jQuery printerBox element to format/arrange the status information
		var printerBox = $("<div>").attr('class','printerBox');
		
		//Printer Name
		var printerName = $("<div>")
			.attr('class','printerTitle')
			.html("<a href=\"http://" + printer.ip + "/hp/device/DeviceStatus/Index\" target='_new'>"+printer.name+"</a>")
			;
		printerBox.append(printerName);
		
		//add current status
		//change color based on status
		var divCurrentStatus = $("<div>")
			.attr('class','cell')
			.html("Status: "+currentStatus);

		//parse text of the current status
		//if it contains jam/'load tray 1'/error/open, decrement status value by 3
		//this ensures that these statuses will put the printer in Urgent state
		//other than that, it's fine
		if (currentStatus.match(/(jam)|(load\ tray\ 1)|(error)|(open)|(CLOSE\ FRONT\ OR\ LEFT\ DOOR)|(Jams)|(Jams\ in\ right\ door) /i)) {
			divCurrentStatus.css('borderLeftColor','red');
			statusValue -= 3;
		} else if (currentStatus.match(/(ready)/i)) {
			divCurrentStatus.css('borderLeftColor','green');
		} else {
			divCurrentStatus.css('borderLeftColor','orange');
			statusValue += 0.2;
		}
		printerBox.append(divCurrentStatus);
		
		//Toner & Cyan
		var divTNM = $("<div>")
			.attr('class','cellTitle')
			.html("Toner; Cyan; Magenta; Yellow &amp; Maintenance")

		//Toner & Magenta
		//var divTNM = $("<div>")
		//	.attr('class','cellTitle')
		//	.html("Toner &amp; Magenta")

		//Toner & Yellow
		//var divTNM = $("<div>")
		//	.attr('class','cellTitle')
		//	.html("Toner &amp; Yellow")

		//Toner & Fuser
		//var divTNM = $("<div>")
		//	.attr('class','cellTitle')
		//	.html("Toner &amp; Fuser")
		;
		printerBox.append(divTNM);
		
		//add current toner
		//change background color based on status
		//less than 1% will decrement status value by 3, puts printer in Urgent state
		//less than 5% will incrememt status value by 0.3
		//otherwise, increment status value by 1.0
		var divCurrentToner = $("<div>")
			.attr('class','cell')
			.html("Toner: "+currentToner)
		;		
		if (currentToner == "N/A") {	
			divCurrentToner.css('borderLeftColor','orange');
			statusValue += 0.0;
		} else if (Number(currentToner.match(/\d+/)[0]) < 1) {
			divCurrentToner.css('borderLeftColor','red');
			statusValue -= 3;
		} else if (Number(currentToner.match(/\d+/)[0]) < 10) {
			divCurrentToner.css('borderLeftColor','orange');
			statusValue += 0.3;
		} else {
			divCurrentToner.css('borderLeftColor','green');
			statusValue += 1;
		}
		printerBox.append(divCurrentToner);
		
		//add current Cyan
		//change color based on status
		//less than 5% will decrease status value by 0.5
		//otherwise, increment status value by 0.5
		var divCurrentCyan = $("<div>")
			.attr('class','cell')
			.html("Cyan Cartridge: "+currentCyan)
			;
		if (currentCyan == "N/A") {
			divCurrentCyan.css('borderLeftColor','orange');
			statusValue += 0.5;
		} else if (Number(currentCyan.match(/\d+/)[0]) < 5) {
			divCurrentCyan.css('borderLeftColor','orange');
			statusValue -= 0.5;
		} else {
			divCurrentCyan.css('borderLeftColor','green');
			statusValue += 0.5;
		}
		printerBox.append(divCurrentCyan);

		//add current Magenta
		//change color based on status
		//less than 5% will decrease status value by 0.5
		//otherwise, increment status value by 0.5
		var divCurrentMagenta = $("<div>")
			.attr('class','cell')
			.html("Magenta Cartridge: "+currentMagenta)
			;
		if (currentMagenta == "N/A") {
			divCurrentCyan.css('borderLeftColor','orange');
			statusValue += 0.5;
		} else if (Number(currentMagenta.match(/\d+/)[0]) < 5) {
			divCurrentMagenta.css('borderLeftColor','orange');
			statusValue -= 0.5;
		} else {
			divCurrentMagenta.css('borderLeftColor','green');
			statusValue += 0.5;
		}
		printerBox.append(divCurrentMagenta);

		//add current Yellow
		//change color based on status
		//less than 5% will decrease status value by 0.5
		//otherwise, increment status value by 0.5
		var divCurrentYellow = $("<div>")
			.attr('class','cell')
			.html("Yellow Cartridge: "+currentCyan)
			;
		if (currentYellow == "N/A") {
			divCurrentYellow.css('borderLeftColor','orange');
			statusValue += 0.5;
		} else if (Number(currentYellow.match(/\d+/)[0]) < 5) {
			divCurrentYellow.css('borderLeftColor','orange');
			statusValue -= 0.5;
		} else {
			divCurrentYellow.css('borderLeftColor','green');
			statusValue += 0.5;
		}
		printerBox.append(divCurrentYellow);

		//add current Fuser
		//change color based on status
		//less than 5% will decrease status value by 0.5
		//otherwise, increment status value by 0.5
		var divCurrentMaintenance = $("<div>")
			.attr('class','cell')
			.html("Maintenance Kit: "+currentCyan)
			;
		if (currentMaintenance == "N/A") {
			divCurrentMaintenance.css('borderLeftColor','orange');
			statusValue += 0.5;
		} else if (Number(currentMaintenance.match(/\d+/)[0]) < 5) {
			divCurrentMaintenance.css('borderLeftColor','orange');
			statusValue -= 0.5;
		} else {
			divCurrentMaintenance.css('borderLeftColor','green');
			statusValue += 0.5;
		}
		printerBox.append(divCurrentMaintenance);

		
		// Paper Trays
		var divPT = $("<div>")
			.attr('class','cellTitle')
			.html("Paper Trays")
		;
		printerBox.append(divPT);
		
		//iterate through trays
		//keep track of total tray count, if Tray 1 exists, decrement tray count by 1
		//if tray status reads "OK" increment status value by (1/trayCount)
		//	if all trays that are not Tray 1 are OK, status value will increase by 1.0
		//if tray status has numbers in it
		//	parse out the number
		//		if it's 40,  increment status value by (1/trayCount), make it green
		//		if it's 10, make it orange, don't increment status value
		var trayCount = trays.length;
		for (var i=0; i<trays.length; i++) {
			var tray = trays[i];
			var divTray = $("<div>")
				.attr('class','cell')
				.html(tray.name + ": " + tray.status)
				;

			if (tray.name.match(/tray\s1/i)) {
				trayCount--;
			} else {
				if (tray.status.match(/ok/i)) {
					divTray.css('borderLeftColor','green');
					statusValue += 1/trayCount;
				} else if (tray.status.match(/\d+/)) {
					if (Number(tray.status.match(/\d+/)[0]) >= 40) {
						divTray.css('borderLeftColor','green');
						statusValue += 1/trayCount;						
					} else if (Number(tray.status.match(/\d+/)[0]) >= 10) {
						divTray.css('borderLeftColor','orange');
					
					} else {
						divTray.css('borderLeftColor','red');
					}
				} else {
					divTray.css('borderLeftColor','red');
				}
			}
				
			
			printerBox.append(divTray);
		}
		
		// Displays the status value, integer for determing which category to place printer in
		//Uncomment for testing/debugging
		//divMathFloor = $("<div>")
		//	.attr('class','cell')
		//	.html(Math.floor(statusValue))
		//	;
		//printerBox.append(divMathFloor);
		
		//remove this printer from the "no response" section
		//if there are no more printers in the "no response" section, hide it
		$("div.pending"+printer.nameShort).remove();
		var divNoResponse = $("div",$("div#noresponse"));
		if (divNoResponse.size() == 0)
			$("div#noresponse").hide();				

		//determine which category the printer should be added to by its status value
		if (Math.floor(statusValue) < 1) {
			$("div#urgent").show().append(printerBox);
			alert(printer.name + " NEEDS SERVICE IMMEDIATELY");
		} else if (Math.floor(statusValue) < 2) {
			$("div#needservice").show().append(printerBox);
		} else {
			$("div#goodservice").show().append(printerBox);

		}
	})
	.error( function() {
		//printers[i]["error"] = true;
	});

}

